//  MOD.rs
//    by Lut99
//
//  Created:
//    05 Mar 2025, 17:31:22
//  Last edited:
//    06 Mar 2025, 10:34:52
//  Auto updated?
//    Yes
//
//  Description:
//!   Provides traits for AST nodes to serialize them to nodes for the
//!   excellent [railroad](::railroad)-crate.
//

// Module definitions
pub mod diagram;
mod impls;

// Re-exports
pub use diagram::Diagram;
pub use railroad;


/***** LIBRARY *****/
/// Marks your node as convertible into a [`Diagram`] or a [`railroad` Node](railroad::Node).
pub trait Railroad {
    /// The type of [`railroad`-node](railroad::Node)-node to which this node is serialized.
    type Output: 'static + railroad::Node;


    /// Serializes this node into a [`railroad`-node](railroad::Node).
    ///
    /// # Returns
    /// A [`Node`](railroad::Node) that can be rendered as a railroad diagram.
    fn to_railroad_node() -> Self::Output;

    /// Serializes a referral to this node instead of the node itself.
    ///
    /// This is useful for when the node itself occurs multiple times and is very large. Instead,
    /// the node generated by this function can be used to refer to its label instead.
    ///
    /// By default, it will generate a label that bears the output of
    /// [`type_name()`](std::any::type_name) for this type.
    ///
    /// # Returns
    /// A [`NonTerminal`](railroad::NonTerminal) that can be rendered as a railroad diagram.
    #[inline]
    fn to_railroad_label() -> railroad::NonTerminal { railroad::NonTerminal::new(std::any::type_name::<Self>().into()) }

    /// Convenience function for generation a diagram that only shows this node.
    ///
    /// Usually, you don't need to override this. Only your toplevel node should to make sure that
    /// it plus any nonterminals in your tree are rendered correctly.
    ///
    /// By default, it will create a new [`Diagram`]-object with only the
    /// [serialization](Railroad::to_railroad_node()) of this node added to it.
    #[inline]
    fn to_railroad_diagram() -> Diagram<'static> { Diagram::new(Self::to_railroad_node()) }
}



/// Marks that a delimiting node can be converted into a [`Diagram`] or a
/// [`railroad` Node](railroad::Node).
pub trait RailroadDelim: Railroad {
    /// The type of [`railroad`-node](railroad::Node)-node to which this node is serialized.
    type DelimOutput: 'static + railroad::Node;


    /// Serializes this node into a [`railroad` Node](railroad::Node).
    ///
    /// # Arguments
    /// - `node`: Some other [`railroad` Node](railroad::Node) to wrap this delimited node around.
    ///
    /// # Returns
    /// A [`Node`](railroad::Node) that can be rendered as a railroad diagram.
    fn to_railroad_delim_node<'n>(node: impl 'static + railroad::Node) -> Self::DelimOutput;
}
